#!/bin/sh

SESSION=$USER

# Create TMUX session:
tmux -2 new-session -d -s $SESSION
tmux new-window -t $SESSION:1 -n 'Monitor'

# Generate layout
tmux split-window -v
tmux select-pane -t 0
tmux split-window -h
tmux select-pane -t 0
tmux resize-pane -x 50 -y 23

# Album art pane:
tmux select-pane -t 0
tmux send-keys ".ncmpcpp/cover.sh" C-m

# Shell pane:
tmux select-pane -t 1
tmux send-keys "fish" C-m

# Monitor pane:
tmux select-pane -t 2
tmux send-keys "gotop -r 0.25 -i enp16s0f0 -a" C-m

# Attach to session:
tmux -2 attach-session -t $SESSION
